//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.NerdLab;

[assembly: RegisterDocumentType(PrivacyPage.CLASS_NAME, typeof(PrivacyPage))]

namespace CMS.DocumentEngine.Types.NerdLab
{
	/// <summary>
	/// Represents a content item of type PrivacyPage.
	/// </summary>
	public partial class PrivacyPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "NerdLab.PrivacyPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with PrivacyPage fields.
		/// </summary>
		private readonly PrivacyPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PrivacyPageID.
		/// </summary>
		[DatabaseIDField]
		public int PrivacyPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PrivacyPageID"), 0);
			}
			set
			{
				SetValue("PrivacyPageID", value);
			}
		}


		/// <summary>
		/// PrivacyContent.
		/// </summary>
		[DatabaseField]
		public string PrivacyContent
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PrivacyContent"), @"");
			}
			set
			{
				SetValue("PrivacyContent", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PrivacyPage fields.
		/// </summary>
		[RegisterProperty]
		public PrivacyPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PrivacyPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PrivacyPageFields : AbstractHierarchicalObject<PrivacyPageFields>
		{
			/// <summary>
			/// The content item of type PrivacyPage that is a target of the extended API.
			/// </summary>
			private readonly PrivacyPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PrivacyPageFields" /> class with the specified content item of type PrivacyPage.
			/// </summary>
			/// <param name="instance">The content item of type PrivacyPage that is a target of the extended API.</param>
			public PrivacyPageFields(PrivacyPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PrivacyPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PrivacyPageID;
				}
				set
				{
					mInstance.PrivacyPageID = value;
				}
			}


			/// <summary>
			/// PrivacyContent.
			/// </summary>
			public string PrivacyContent
			{
				get
				{
					return mInstance.PrivacyContent;
				}
				set
				{
					mInstance.PrivacyContent = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PrivacyPage" /> class.
		/// </summary>
		public PrivacyPage() : base(CLASS_NAME)
		{
			mFields = new PrivacyPageFields(this);
		}

		#endregion
	}
}