//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.NerdLab;

[assembly: RegisterDocumentType(HomeItem.CLASS_NAME, typeof(HomeItem))]

namespace CMS.DocumentEngine.Types.NerdLab
{
	/// <summary>
	/// Represents a content item of type HomeItem.
	/// </summary>
	public partial class HomeItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "NerdLab.HomeItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with HomeItem fields.
		/// </summary>
		private readonly HomeItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HomeItemID.
		/// </summary>
		[DatabaseIDField]
		public int HomeItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("HomeItemID"), 0);
			}
			set
			{
				SetValue("HomeItemID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"Home item title...");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string Description
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Description"), @"Home item description...");
			}
			set
			{
				SetValue("Description", value);
			}
		}


		/// <summary>
		/// ProgressText.
		/// </summary>
		[DatabaseField]
		public string ProgressText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ProgressText"), @"Progress text...");
			}
			set
			{
				SetValue("ProgressText", value);
			}
		}


		/// <summary>
		/// ProgressPercentage.
		/// </summary>
		[DatabaseField]
		public int ProgressPercentage
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProgressPercentage"), 10);
			}
			set
			{
				SetValue("ProgressPercentage", value);
			}
		}


		/// <summary>
		/// ProgressColor.
		/// </summary>
		[DatabaseField]
		public int ProgressColor
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProgressColor"), 0);
			}
			set
			{
				SetValue("ProgressColor", value);
			}
		}


		/// <summary>
		/// LinkTo.
		/// </summary>
		[DatabaseField]
		public string LinkTo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LinkTo"), "");
			}
			set
			{
				SetValue("LinkTo", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with HomeItem fields.
		/// </summary>
		[RegisterProperty]
		public HomeItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with HomeItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HomeItemFields : AbstractHierarchicalObject<HomeItemFields>
		{
			/// <summary>
			/// The content item of type HomeItem that is a target of the extended API.
			/// </summary>
			private readonly HomeItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HomeItemFields" /> class with the specified content item of type HomeItem.
			/// </summary>
			/// <param name="instance">The content item of type HomeItem that is a target of the extended API.</param>
			public HomeItemFields(HomeItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HomeItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.HomeItemID;
				}
				set
				{
					mInstance.HomeItemID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.Description;
				}
				set
				{
					mInstance.Description = value;
				}
			}


			/// <summary>
			/// ProgressText.
			/// </summary>
			public string ProgressText
			{
				get
				{
					return mInstance.ProgressText;
				}
				set
				{
					mInstance.ProgressText = value;
				}
			}


			/// <summary>
			/// ProgressPercentage.
			/// </summary>
			public int ProgressPercentage
			{
				get
				{
					return mInstance.ProgressPercentage;
				}
				set
				{
					mInstance.ProgressPercentage = value;
				}
			}


			/// <summary>
			/// ProgressColor.
			/// </summary>
			public int ProgressColor
			{
				get
				{
					return mInstance.ProgressColor;
				}
				set
				{
					mInstance.ProgressColor = value;
				}
			}


			/// <summary>
			/// LinkTo.
			/// </summary>
			public IEnumerable<global::CMS.DocumentEngine.PageRelatedItem> LinkTo
			{
				get
				{
					return global::CMS.DataEngine.Internal.JsonDataTypeConverter.ConvertToModels<global::CMS.DocumentEngine.PageRelatedItem>(mInstance.LinkTo);
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="HomeItem" /> class.
		/// </summary>
		public HomeItem() : base(CLASS_NAME)
		{
			mFields = new HomeItemFields(this);
		}

		#endregion
	}
}