//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.NerdLab;

[assembly: RegisterDocumentType(FeatureItem.CLASS_NAME, typeof(FeatureItem))]

namespace CMS.DocumentEngine.Types.NerdLab
{
	/// <summary>
	/// Represents a content item of type FeatureItem.
	/// </summary>
	public partial class FeatureItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "NerdLab.FeatureItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with FeatureItem fields.
		/// </summary>
		private readonly FeatureItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FeatureItemID.
		/// </summary>
		[DatabaseIDField]
		public int FeatureItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FeatureItemID"), 0);
			}
			set
			{
				SetValue("FeatureItemID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"Feature item title");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string Description
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Description"), @"Feature item description...");
			}
			set
			{
				SetValue("Description", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FeatureItem fields.
		/// </summary>
		[RegisterProperty]
		public FeatureItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FeatureItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FeatureItemFields : AbstractHierarchicalObject<FeatureItemFields>
		{
			/// <summary>
			/// The content item of type FeatureItem that is a target of the extended API.
			/// </summary>
			private readonly FeatureItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FeatureItemFields" /> class with the specified content item of type FeatureItem.
			/// </summary>
			/// <param name="instance">The content item of type FeatureItem that is a target of the extended API.</param>
			public FeatureItemFields(FeatureItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FeatureItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FeatureItemID;
				}
				set
				{
					mInstance.FeatureItemID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.Description;
				}
				set
				{
					mInstance.Description = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FeatureItem" /> class.
		/// </summary>
		public FeatureItem() : base(CLASS_NAME)
		{
			mFields = new FeatureItemFields(this);
		}

		#endregion
	}
}