//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.NerdLab;

[assembly: RegisterDocumentType(Product.CLASS_NAME, typeof(Product))]

namespace CMS.DocumentEngine.Types.NerdLab
{
	/// <summary>
	/// Represents a content item of type Product.
	/// </summary>
	public partial class Product : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "NerdLab.Product";


		/// <summary>
		/// The instance of the class that provides extended API for working with Product fields.
		/// </summary>
		private readonly ProductFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ProductID.
		/// </summary>
		[DatabaseIDField]
		public int ProductID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProductID"), 0);
			}
			set
			{
				SetValue("ProductID", value);
			}
		}


		/// <summary>
		/// VideoLink.
		/// </summary>
		[DatabaseField]
		public string VideoLink
		{
			get
			{
				return ValidationHelper.GetString(GetValue("VideoLink"), @"");
			}
			set
			{
				SetValue("VideoLink", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string Description
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Description"), @"");
			}
			set
			{
				SetValue("Description", value);
			}
		}


		/// <summary>
		/// ImageLink.
		/// </summary>
		[DatabaseField]
		public string ImageLink
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageLink"), @"");
			}
			set
			{
				SetValue("ImageLink", value);
			}
		}


		/// <summary>
		/// UsecaseTitle.
		/// </summary>
		[DatabaseField]
		public string UsecaseTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("UsecaseTitle"), @"");
			}
			set
			{
				SetValue("UsecaseTitle", value);
			}
		}


		/// <summary>
		/// UsecaseDescription.
		/// </summary>
		[DatabaseField]
		public string UsecaseDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("UsecaseDescription"), @"");
			}
			set
			{
				SetValue("UsecaseDescription", value);
			}
		}


		/// <summary>
		/// ProductPricingTitle.
		/// </summary>
		[DatabaseField]
		public string ProductPricingTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ProductPricingTitle"), @"");
			}
			set
			{
				SetValue("ProductPricingTitle", value);
			}
		}


		/// <summary>
		/// ProductPricingDescription.
		/// </summary>
		[DatabaseField]
		public string ProductPricingDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ProductPricingDescription"), @"");
			}
			set
			{
				SetValue("ProductPricingDescription", value);
			}
		}


		/// <summary>
		/// StatusTitle.
		/// </summary>
		[DatabaseField]
		public string StatusTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("StatusTitle"), @"");
			}
			set
			{
				SetValue("StatusTitle", value);
			}
		}


		/// <summary>
		/// StatusDescription.
		/// </summary>
		[DatabaseField]
		public string StatusDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("StatusDescription"), @"");
			}
			set
			{
				SetValue("StatusDescription", value);
			}
		}


		/// <summary>
		/// StatusProgressColor.
		/// </summary>
		[DatabaseField]
		public int StatusProgressColor
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("StatusProgressColor"), 0);
			}
			set
			{
				SetValue("StatusProgressColor", value);
			}
		}


		/// <summary>
		/// StatusProgressPercentage.
		/// </summary>
		[DatabaseField]
		public int StatusProgressPercentage
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("StatusProgressPercentage"), 10);
			}
			set
			{
				SetValue("StatusProgressPercentage", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Product fields.
		/// </summary>
		[RegisterProperty]
		public ProductFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Product fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ProductFields : AbstractHierarchicalObject<ProductFields>
		{
			/// <summary>
			/// The content item of type Product that is a target of the extended API.
			/// </summary>
			private readonly Product mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ProductFields" /> class with the specified content item of type Product.
			/// </summary>
			/// <param name="instance">The content item of type Product that is a target of the extended API.</param>
			public ProductFields(Product instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ProductID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ProductID;
				}
				set
				{
					mInstance.ProductID = value;
				}
			}


			/// <summary>
			/// VideoLink.
			/// </summary>
			public string VideoLink
			{
				get
				{
					return mInstance.VideoLink;
				}
				set
				{
					mInstance.VideoLink = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.Description;
				}
				set
				{
					mInstance.Description = value;
				}
			}


			/// <summary>
			/// ImageLink.
			/// </summary>
			public string ImageLink
			{
				get
				{
					return mInstance.ImageLink;
				}
				set
				{
					mInstance.ImageLink = value;
				}
			}


			/// <summary>
			/// UsecaseTitle.
			/// </summary>
			public string UsecaseTitle
			{
				get
				{
					return mInstance.UsecaseTitle;
				}
				set
				{
					mInstance.UsecaseTitle = value;
				}
			}


			/// <summary>
			/// UsecaseDescription.
			/// </summary>
			public string UsecaseDescription
			{
				get
				{
					return mInstance.UsecaseDescription;
				}
				set
				{
					mInstance.UsecaseDescription = value;
				}
			}


			/// <summary>
			/// ProductPricingTitle.
			/// </summary>
			public string PricingTitle
			{
				get
				{
					return mInstance.ProductPricingTitle;
				}
				set
				{
					mInstance.ProductPricingTitle = value;
				}
			}


			/// <summary>
			/// ProductPricingDescription.
			/// </summary>
			public string PricingDescription
			{
				get
				{
					return mInstance.ProductPricingDescription;
				}
				set
				{
					mInstance.ProductPricingDescription = value;
				}
			}


			/// <summary>
			/// StatusTitle.
			/// </summary>
			public string StatusTitle
			{
				get
				{
					return mInstance.StatusTitle;
				}
				set
				{
					mInstance.StatusTitle = value;
				}
			}


			/// <summary>
			/// StatusDescription.
			/// </summary>
			public string StatusDescription
			{
				get
				{
					return mInstance.StatusDescription;
				}
				set
				{
					mInstance.StatusDescription = value;
				}
			}


			/// <summary>
			/// StatusProgressColor.
			/// </summary>
			public int StatusProgressColor
			{
				get
				{
					return mInstance.StatusProgressColor;
				}
				set
				{
					mInstance.StatusProgressColor = value;
				}
			}


			/// <summary>
			/// StatusProgressPercentage.
			/// </summary>
			public int StatusProgressPercentage
			{
				get
				{
					return mInstance.StatusProgressPercentage;
				}
				set
				{
					mInstance.StatusProgressPercentage = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Product" /> class.
		/// </summary>
		public Product() : base(CLASS_NAME)
		{
			mFields = new ProductFields(this);
		}

		#endregion
	}
}